### ISSUE TITLE
[Enhancement] Add AuthContext to keep user data

### ISSUE THREAD

**Issue by raynelfss** [ColleagueApp/colleague#15]
## Overview
Back when I worked on [Booked](https://github.com/MonCaptain/bookd) we used `AuthContext` to create a session in the frontend and keep login information stored in the front-end.

## Proposed feature
Adding `AuthContext` to store session information. This could prevent us from constantly calling the backend to request user information while also keeping a secured session open in the front-end.

### Additional context
- Check the following [AuthContext](https://github.com/MonCaptain/bookd/blob/main/client/src/contexts/AuthContext.jsx) that was set up in a previous project.
- Check the following [article](https://dev.to/dayvster/use-react-context-for-auth-288g) for further information on what to do.

**Comment by raynelfss** [comment]
Please feel free to bring up any alternatives that could be considered @ColleagueApp/development! I might be keeping #14 on hold until we find a solution.

**Comment by nhusan** [comment]
I like the implementation from the [article](https://dev.to/dayvster/use-react-context-for-auth-288g). All the logic is modularized, which may simplify maintenance and make it easier to add new functionality in the long run.
