### ISSUE TITLE
[Enhancement] Navigation Bar component

### ISSUE THREAD

**Issue by raynelfss** [ColleagueApp/colleague#6]
## Overview
We need a navigation bar that includes a search feature, our logo, and other components.

## Proposed feature
A navigation bar that includes the features mentioned before.

### Additional context
Inspiration:
- ![image](https://github.com/ColleagueApp/colleague/assets/87539502/340dd6e0-f56e-498c-bfa3-1c2f0e947478)

Extra resources:
- [Chakra Template for Navbar](https://chakra-templates.vercel.app/navigation/navbar)

**Comment by Kedarnath-Rothe** [comment]
Please assign this task to me under hactoberfest

**Comment by raynelfss** [comment]
> Please assign this task to me under Hacktoberfest

Hello @Kedarnath-Rothe! I appreciate your wanting to contribute to our project. However, this repository was not registered under Hacktoberfest. I suggest looking into other repositories under the topic [#hacktoberfest-2023](https://github.com/topics/hacktoberfest-2023). Good luck hacking!
