### ISSUE TITLE
[Chore] File structure for the Front-End

### ISSUE THREAD

**Issue by raynelfss** [ColleagueApp/colleague#7]
## Overview:

To avoid cluttering, a file structure system should be in place.

## Description:

As we are dealing with a web dev project with lots of files and lines of code needed, we should consider how these files are going to be organized.

I have found some resources online about ways of organizing files in a React project and found one that should work well as a potential file structure system:

- ![image](https://github.com/ColleagueApp/colleague/assets/87539502/2c9534ee-6cb8-4fbe-851d-e35d1f3b322d)
*from [This post](https://blog.webdevsimplified.com/2022-07/react-folder-structure/)*

I'd like to see if any of @ColleagueApp/development has an opinion on this.

Thanks :)

**Comment by hMRZQ21** [comment]
Looks good, if the list of reusable component grows, we can group them inside more files

**Comment by jedrm** [comment]
I suggest having more folders for things like `stores`, `pages`, `services`, and `utils`. There are some other ones but those come to mind.

**Comment by raynelfss** [comment]
> I suggest having more folders for things like `stores`, `pages`, `services`, and `utils`. There are some other ones but those come to mind.

Do you have an example we could use in the case?
